### ISSUE TITLE
Write comprehensive parser tests for characters

### ISSUE THREAD

**Issue by Janiczek** [elm-in-elm/compiler#11]
This means:

- [ ] find all the ways characters can be written in Elm (`\u{...}`? `\x{...}`? straight-up emoji in the source code? something else?)
- [ ] add those as tests to the "literal char" section of ParserTest.elm so that the tests exercise all the possibilities and truthfully tell us what's done and what's not
- [ ] update the "what's done" table in README - parser tests for characters

**Comment by aaronjanse** [comment]
Hmmm, I can't get `\x{...}` to compile. The elm compiler seems to imply it doesn't exist. Is that correct?

```
Backslashes always start escaped characters, but I do not recognize this one:

559|                   , "'\x{3a}'"
                           ^
Maybe there is some typo?

Hint: Valid escape characters include:

    \n
    \r
    \t
    \"
    \'
    \\
    \u{03BB}
```

**Comment by Janiczek** [comment]
I believe it did exist in previous versions of Elm and got changed into the `\u` syntax. Thanks for checking!
