### ISSUE TITLE
Left field idea: rename types to `T` and drop exposing

### ISSUE THREAD

**Issue by harrysarson** [elm-in-elm/compiler#113]
We have a whole lot of types like:

- `Elm.Data.Exposing.Exposing`
- `Elm.Data.ModuleName.ModuleName`

where there is a module fundamentally there to define a type and some helper functions. My idea would be to rename the type defined by this module to `T`. Therefore we would have:

- `Elm.Data.Exposing.T`
- `Elm.Data.ModuleName.T`

and we would not have to write `import Elm.Data.Exposing exposing (Exposing)` but could instead use `Elm.Data.Exposing.T` directly. Definitely, cons to this idea but I thought worth throwing it out.

**Comment by Janiczek** [comment]
From a first read, my absolutely first reaction is that I like

```elm
import Elm.Data.ModuleName {- as ModuleName -} exposing (ModuleName)

stuff : ModuleName
```

more than

```elm
import Elm.Data.ModuleName

stuff : Elm.Data.ModuleName.T
```

or even

```elm
import Elm.Data.ModuleName as ModuleName

stuff : ModuleName.T
```

I'll mull this over a bit, maybe it'll grow on me :slightly\_smiling\_face: 

Do you think there are advantages to this? Is it pain in the neck to do `import Elm.Data.Foo as Foo exposing (Foo)`? What's the motivation?

**Comment by harrysarson** [comment]
> From a first read, my absolutely first reaction is that I like ...  more than .. or even

Thinking about this some more I do have to agree with you. I think the gist of my issue is that I see something like

```elm
func : String -> ModuleName -> Exposing -> Module
```

and have to scroll all the way up to the top of the current elm file to find the file that defines of each type. Whereas with

```elm
func : String -> Elm.Data.ModuleName.T -> Elm.Data.Exposing.T -> Elm.Data.Module.T
``` 

I know instantly where to look.

**Comment by harrysarson** [comment]
Closing, I think `cons > pros` here.
