### ISSUE TITLE
[Security] Workflow deploy-to-gh-pages.yml is using vulnerable action JamesIves/github-pages-deploy-action

### ISSUE THREAD

**Issue by igibek** [elm-in-elm/compiler#135]
The workflow deploy-to-gh-pages.yml is referencing action JamesIves/github-pages-deploy-action using references 3.4.9. However this reference is missing the commit [661e33871bce8107c9af083f7415176608dce40e](https://github.com/JamesIves/github-pages-deploy-action/commits/661e33871bce8107c9af083f7415176608dce40e) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by Janiczek** [comment]
Thanks I'll take a look at this.

**Comment by Janiczek** [comment]
Should be fixed now as I've upgraded `JamesIves/github-pages-deploy-action` to 4.1.8: https://github.com/elm-in-elm/compiler/commit/1de225a324efd2334b255ed3017b3d6da7473ed3#diff-a8addec63f583d6333a3f6265f4dd0429eef20aefccbbbd15660029d66981dc1R31
