### ISSUE TITLE
Add Nix expression for the project

### ISSUE THREAD

**Issue by Janiczek** [elm-in-elm/compiler#16]
I guess with the current tooling that should mean:
* user can run `nix-shell` inside the project and get a shell with `elm`, `elm-format`, `elm-test`, `node` (v10+) and `make` ready to use. (Bonus points for `elm-analyse`)

If you know more about Nix (I know awfully little about it) and think it should / can do more, I'm all ears!

**Comment by aaronjanse** [comment]
> If you know more about Nix (I know awfully little about it) and think it should / can do more, I'm all ears!

No problem. What you described is exactly what's customary for using Nix in the development cycle, spawning a shell with project-specific software installed.

Eventually, as a NixOS user, I'd love to package this for other Nix users to install, but there's a lot to do before this project is ready to be packaged & published.

**Comment by Janiczek** [comment]
Great, I agree with (sometime later when the CLI is actually useful) adding that too. But yeah that's not right now :)
