### ISSUE TITLE
Write comprehensive parser tests for strings

### ISSUE THREAD

**Issue by Janiczek** [elm-in-elm/compiler#21]
This means:

- [ ] add tests to "literal string" section of ParserTest.elm about
  - [ ] multiline string (`"""abc"""`)
  - [ ] how do escapes work in normal vs multiline strings (`"{\"foo\":1}"` vs `"""{"foo":1}"""`)
  - [ ] that multiline strings actually parse newlines!
- [ ] update the "what's done" table in README - parser tests for strings

Some of the tests should fail - not implemented yet.
Fixing the parser is not needed in this ticket (can be in a separate one)

**Comment by aaronjanse** [comment]
I think that multiline strings should have their own parser block (e.g. literalMultilineString) if not already.

-------- Original Message --------
