### ISSUE TITLE
Add support for tuples and 3-tuples

### ISSUE THREAD

**Issue by Janiczek** [elm-in-elm/compiler#34]
This means:

- [ ] add `Tuple (Expr, Expr)` and `Triple (Expr, Expr, Expr)` constructors to `Frontend.Expr` type... solve any compiler errors that arise as a result (`emitExpr` etc)
- [ ] add tests that show all the various ways these can be written in. Don't think about newlines for now (those will be dealt with later), but write tests to see tuples work with and without spaces in between. Eg.:
  - [ ] `(1,2)`, `( 1, 2 )`
  - [ ] `(1,2,3)`, `( 1, 2, 3 )`
- [ ] implement type inference - it should be pretty straighforward:
  - [ ] if items have types A and B, the tuple has type `(A, B)`. (Yeah, you'll have to create new `Type` constructors to account for this)
  - [ ] similarly for 3-tuples ("triples" - I don't like that name though :slightly_frowning_face: ) - items with types A, B, C :arrow_right: 3-tuple has type `(A, B, C)`
- [ ] add emit tests too:
  - [ ] Elm's `(1, 2)` :arrow_right: JavaScript's `[1, 2]`, similarly with the 3-tuples
- [ ] implement emitting (`emitExpr`) to pass the emit tests above
- [ ] update the "what's done" table in README for tuples and 3-tuples: parser tests, type inference, emit and emit tests... but not parsers.

If you get stuck on anything, ask here or on Discord! We'll help you :slightly_smiling_face: 

## Out of scope :x: :x: :x:

- [ ] tests for newlines support in tuples and 3-tuples
- [ ] parser for tuples and 3-tuples

## Bonus points :trophy: 

- [ ] think of a better name for the 3-tuple constructor than `Triple`

**Comment by harrysarson** [comment]
An alternative representation of a tuple is `Tuple Expr Expr (Maybe Expr)` which can handle both 2-tuples and 3-tuples.

I thought it might be worth a thought (this is what the elm compiler uses).

**Comment by Janiczek** [comment]
@harrysarson Yeah, good point, I've also looked into what the official Elm compiler uses just (to see how they name this) - but I probably like separate constructors better than mixing them together like that.

**Comment by Felix3142** [comment]
Hi all! I love the idea of this project and will fork it and take up one of these callenges but first my idea for a better name for a 3-Tuple is, of course, a Truple :-)
Trekkies might go for Tibble ;-)  
Glad we no longer need Qruples/Quaples or Pentles!

**Comment by Janiczek** [comment]
Closed by #45
