### ISSUE TITLE
Implement parser for tuples and 3-tuples

### ISSUE THREAD

**Issue by Janiczek** [elm-in-elm/compiler#35]
Implement parser for tuples and 3-tuples so that the tests created in #34 are green! :green_heart:

**Comment by halfzebra** [comment]
What do you think of Tuple parsers?

Would it make sense to implement them using a [sequence](https://package.elm-lang.org/packages/elm/parser/latest/Parser#seque) and check the length or a regular pipeline should do the trick?

I'm asking because they have a hard limit on the number of items.

**Comment by Janiczek** [comment]
I'd probably go with a regular pipeline, not `sequence`. That being said, feel free to experiment, we can decide later!
