### ISSUE TITLE
Fuzzing type inference with expressions that type

### ISSUE THREAD

**Issue by szabba** [elm-in-elm/compiler#40]
This means:

* [ ] add an `InferTypesTest.elm` in the test project. (You can skip that if it's already done. #39 might do that)
* [ ] add a `typedExprFuzzer : Type -> Fuzzer Expr` function. This should generate a random expression that conforms to the type.
* [ ] add the above to write a `fuzzInference : Type -> Test` function. This should use `typedExprFuzzer` to test that the random expressions have the input type inferred.
* [ ] add type inference tests of the form `fuzzInference someTypeToCheck`. You can put them in a nested `describe` for grouping.

The idea is that generating expressions that fit a type should be easier than inferring the type of an expression.

If you get stuck on anything, ask here or on Discord! We'll help you :slightly_smiling_face:

## Out of scope :x: :x: :x:

* [ ] Error cases: we are not testing when inference fails and what it reports yet.
* [ ] Configuring the depth of the fuzzed expressions.

**Comment by Janiczek** [comment]
**Re `typedExprFuzzer`:** feel free to split the cases out into smaller focused top-level functions:
```elm
typedExprFuzzer type_ =
  case type_ of
    Int -> intFuzzer
    ...

intFuzzer = ...
...
```

**Re the test suite:** it should run `fuzzInference` on all the types that currently exist, except `Var`. For functions use constant functions

### Potentional gotchas
- `typedExprFuzzer`, `Var` case. As it doesn't make sense to generate `Var` values, feel free to `Debug.todo "don't try to generate Var expressions"`
- `typedExprFuzzer`, `Function` case. I think it should be possible to just do stuff like
```elm
functionFuzzer : Type -> Fuzzer Expr
functionFuzzer returnType =
  case returnType of
    Int ->
      -- rough equivalent of (\_ -> 42)
      Fuzz.constant (Typed.lambda (VarName "_") 999 (Typed.Literal (Int 42)))
    ...
``` 
but if some problems pop up (eg. maybe the lambda's `argumentId`), come share! We'll think of something.
