### ISSUE TITLE
Inference on nested lists

### ISSUE THREAD

**Issue by szabba** [elm-in-elm/compiler#47]
When we try to infer the type for the list `[ [ "" ], [ "" ] ]` we would expect to get `List (List String)`. Instead we get an error complaining about not bein able to unify two type variables:
```
↓ InferTypesTest
↓ Stage.InferType
↓ fuzz exprInfer
✗ List List String

Given List [List [Literal (String "")],List [Literal (String "")]]

    Err (TypeMismatch (List (Var 7)) (List (Var 6)))
    ╷
    │ Expect.equal
    ╵
    Ok (List (List String))
```
It seems like we might be missing some equations. Try looking in the list case inside `Stage.InferTypes.GenerateEquations.generateEquations`.

**Comment by Janiczek** [comment]
The issue might do with the whole List getting its ID in AssignIds phase but its parameter in GenerateEquations phase.

(But it might also be just fine. Just something to consider.)

In any case, printing out the expression right after `assignIds`, then the generated equations and then expression after `substituteAllTypes` should provide enough information into what's missing.
