### ISSUE TITLE
Custom types: parser tests

### ISSUE THREAD

**Issue by Janiczek** [elm-in-elm/compiler#55]
Add parser tests for custom types:
```elm
type Foo
    = Bar
    | Baz Int
    | Quux (Foo, Foo)
```

This will most likely not go through `Frontend.Expr` (as those aren't expressions), but somewhere alongside top-level definitions. Maybe TopLevelDefinition needs to distinguish between expressions and custom types / aliases / port definitions / ...?

### :x: NOT IN SCOPE:
- parameterized custom types (let's do that in some other ticket, keep this as small as we can)

**Comment by halfzebra** [comment]
I'll give a shot at implementing this. 🙂

**Comment by Janiczek** [comment]
Great! I was just thinking these are probably the hottest candidate for somebody to pick up :)
I'll be doing some shuffling of modules that I realized will be nice when fleshing out the library API... so maybe expect some merge conflicts - hopefully nothing too big. And orthogonal to this issue :)

**Comment by Janiczek** [comment]
Just a note that #32 is partially defining data structures for these, so if you're still working on this, have a look there :) `Data.Declaration.DeclarationBody`.

**Comment by halfzebra** [comment]
Should I rebase on top?

I've tried to model it without success, so clearly it looks like a better solution. I'll look into this today.

**Comment by Janiczek** [comment]
You can rebase, sure. Probably depends on what code you already have and want to keep :+1:
