### ISSUE TITLE
Write emit tests for JS

### ISSUE THREAD

**Issue by headbandno2** [elm-in-elm/compiler#7]
Hey. Cool project! 

I wanted to play with it but wanted to know if you could add emit test. It would be great if it just feeds the elm code string and asserted that result matched expected.

**Comment by Janiczek** [comment]
Yeah we will have to add that whole suite of tests! I have created a skeleton in https://github.com/elm-in-elm/compiler/commit/ddb603086ff59f60cb96f3ac1173919afe394526 so ... feel free to add them if you'd like! :slightly_smiling_face: otherwise I will add them in the near future (after the conf).

**Comment by Janiczek** [comment]
To be clear, this is the file that needs work: https://github.com/elm-in-elm/compiler/blob/master/tests/EmitTest.elm
And this is the file it's testing: https://github.com/elm-in-elm/compiler/blob/master/src/compiler/Stage/Emit/JavaScript.elm
