### ISSUE TITLE
Add tests for things like `f a b c < 5`

### ISSUE THREAD

**Issue by showell** [elm-in-elm/compiler#75]
With Pratt parsing, a common bug is that you can successfully parse `f a b c` and `x < 5`, but you can't parse `f a b c < 5`.  We should try adding tests that put somewhat complicated expressions on either sides of the operators.  I quickly skimmed the tests, and I don't believe the tests do much coverage of edge cases.

If you add tests and they pass, then great, leave them in, and we'll have more robust coverage.

If tests fail, either try to make a quick fix (if possible) or open an issue and/or discuss on Discord.

**Comment by Janiczek** [comment]
To anybody looking at this: It needs generic operator calls to be parsed first. (Right now we only support [`+`, `::` and `++` in a hardcoded fashion](https://github.com/elm-in-elm/compiler/blob/53675a5a9c9abfc862bdc6c28a98297511a9c3e4/src/Elm/AST/Frontend.elm#L63-L65).)
