### ISSUE TITLE
Make the let body see the let bindings

### ISSUE THREAD

**Issue by Janiczek** [elm-in-elm/compiler#76]
Currently if you try to put
```elm
module Main exposing (main)

main =
    let
        x = 2
    in
        1 + x
```
into `example-project/src/Main.elm` and run it with `make`, it complains about `x` not being visible in the body. Make it so!

Depending on where the fix is, it might be a good idea to also add a regression unit test somewhere.

Feel free to discuss/ask how to solve this on our Discord!

**Comment by alexshadley** [comment]
I'm taking a look at this right now! Will keep everyone up to date with my progress.

**Comment by Janiczek** [comment]
Let's not forget the `test.failing(` :arrow_right: `test(` change in integration tests when this is done: https://github.com/elm-in-elm/compiler/pull/85#issue-375546599

**Comment by harrysarson** [comment]
CI should fail if we do forget :)

**Comment by gmilleramilar** [comment]
Looks like maybe this is fixed?  The contents of Main.elm in example-project are:

```
module Main exposing (main)

main =
    let
        x = 2
    in
        1 + x
```

**Comment by Janiczek** [comment]
Yup seems like we fixed this as one of the last things before the project took a bit of a hiatus in 2020 😄 Closing :+1:
