### ISSUE TITLE
question about Slack bots

### ISSUE THREAD

**Issue by brandly** [elm-in-elm/compiler#82]
cool project!!

in the readme, it mentions this project unlocks new kinds of Elm applications, like Slack bots. i don't understand!

wouldn't it already be feasible to write a Slack bot in Elm, compile it with the standard compiler, and run the JS in node? what am i missing?

**Comment by Janiczek** [comment]
Hello @brandly and welcome!

You're right about Slack bots being doable in Elm in general. What I had in mind was a specific Slack bot that evaluates Elm code. Perhaps I should clarify in the README 🙃

**Comment by brandly** [comment]
oh, makes sense! i've come across this project a couple times, but i'm mostly interested in it as a learning resource. the line about bots intrigued me, so i just wanted to make sure i wasn't missing anything.

good luck with project! seems like a big undertaking 😄

**Comment by Janiczek** [comment]
Thanks! Yeah it's kinda big but a lot of fun :slightly_smiling_face: 

Re learning resource: I plan to go through the codebase and add a lot more comments to make it more understandable, but I have a few PRs to finish first...

PS: Oh and I've clarified the Slack bot mention in README :wink: 
https://github.com/elm-in-elm/compiler/commit/2e765d5cc2a9dd4d40d68ca58412667ec6efb150
