### ISSUE TITLE
Make sure dependencies in all elm.jsons are the same

### ISSUE THREAD

**Issue by Janiczek** [elm-in-elm/compiler#87]
We have multiple `elm.json` files and the versions of the dependencies are not the same.

Find a solution that complains in CI when they get misaligned.

(At work we have a Haskell script that checks the various versions and tells you the discrepancies; I've talked to @jhrcek about open-sourcing it :slightly_smiling_face: I'll update this issue if/when that happens.)

**Comment by harrysarson** [comment]
We could also try dependabot.com, it would keep reps uptodate as well as in sync

**Comment by Janiczek** [comment]
@harrysarson Do you have experience with that? I'm open to trying it out!

**Comment by harrysarson** [comment]
I use it a lot is very good.

**Comment by harrysarson** [comment]
I don't have access writes to set it up. You do have to give it write access to this repository, I tried to convince Richard to use it for the node test runner but he wasn't happy giving third party write access which was fair enough. Saying that, the company has since been bought by Microsoft and if we dont trust them with access to the repository we probably shouldn't be hosting it on github.

**Comment by Janiczek** [comment]
I must say I probably don't fully understand the results of Dependabot running on our root `/elm.json`. `elm-community/result-extra` has last version `2.4.0`, which I will soon need because of `Result.Extra.join`, but Dependabot says everything's fine with `2.2.1 <= v < 3.0.0`.

Is it perhaps so smart that it sees I don't need it *yet* so it sees `2.2.1` as the lowest acceptable version (it's a package, not an application) where the code still compiles?

Before running it I have been expecting it to bump us to `2.4.0`, honestly.

**Comment by harrysarson** [comment]
I think dependabot rate limits how many pull requests it makes in a hour (?) Or maybe it just misses some of the deps some times. :shrug: 

It has been busy though:
![image](https://user-images.githubusercontent.com/16308754/80651986-ea4a6080-8a6e-11ea-854b-9d1ade44d3b0.png)

**Comment by Janiczek** [comment]
Yup it found everything in the `application` elm.json files, created PRs, I merged them.
I'll give it a while, maybe it will figure the `/` one out :) If not, incompatibility with `package` elm.json files is my running theory, and we can bump that one manually according to CI fails whenever it doesn't find a function somewhere... :smile:

**Comment by Janiczek** [comment]
Thaks again for the suggestion! :heart: We're now using it at work too instead of that homegrown script :)

**Comment by harrysarson** [comment]
Tidy!
